name: Linux Build

on:
    push:
        branches:
            - master

jobs:
    linux_build:
        name: Linux Build
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                rust: [stable]
        steps:
            - uses: actions/checkout@master
            - uses: davidgraeff/rust-musl-action@master
            - name: Build binary
              run: cargo build --target x86_64-unknown-linux-musl --release
