name: Linux Build

on:
    push:
        branches:
            - master

jobs:
    linux_build:
        name: Linux Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
            - uses: davidgraeff/rust-musl-action@master
              run: cargo build --target x86_64-unknown-linux-musl --release
