name: Linux Build

on:
    push:
        branches:
            - master

jobs:
    linux_build:
        name: Linux Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  target: x86_64-unknown-linux-gnu
                  override: true
            - uses: actions-rs/cargo@v1
              with:
                  use-cross: true
                  command: build
                  args: --release --target x86_64-unknown-linux-gnu
