name: Pull Request

on: pull_request

jobs:
    linux_build:
        name: Linux Build
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                rust: [stable]
        steps:
            - uses: actions/checkout@master
            - name: Install latest stable
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
                  components: rustfmt, clippy
            - name: Check format
              uses: actions-rs/cargo@v1
              with:
                  command: fmt
                  args: -- --check
            - name: Clippy check
              uses: actions-rs/cargo@v1
              with:
                  command: clippy
                  args: -- -D warnings
            - name: Tests
              uses: actions-rs/cargo@v1
              with:
                  command: test
